# Generated by Django 5.2.11 on 2026-05-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences_studentprofile_activesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', help_text="Designates the user's role on the platform.", max_length=20),
        ),
    ]
