# Generated by Django 5.2.11 on 2026-04-04 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_remove_enrollment_progress_course_avg_rating_and_more'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSessionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('raw_emotion_log', models.JSONField(default=list, help_text='Full EmotionEvent array from the client session')),
                ('profile_output', models.JSONField(default=dict, help_text='LLM profiler output (engagement arc, recommendations, etc.)')),
                ('engagement_score', models.FloatField(blank=True, help_text='Overall engagement score 0.0-1.0 from profiler', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_profiles', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Session Profile',
                'verbose_name_plural': 'Student Session Profiles',
                'db_table': 'student_session_profiles',
                'ordering': ['-session_date'],
            },
        ),
    ]
