# Generated by Django 5.2.11 on 2026-04-04 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_studentsessionprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sessions_count', models.IntegerField(default=0)),
                ('profile_summary', models.TextField(blank=True, default='', help_text='Concise plain-English paragraph (max 5 sentences) written by the profiler LLM. This is what LearnPal reads at session start.')),
                ('profile_data', models.JSONField(default=dict, help_text='Structured data used by the profiler LLM to rewrite intelligently. Keys: learning_style_signals, engagement_patterns, emotional_tendencies, recommended_approaches, topics_of_difficulty, topics_of_strength.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Learning Profile',
                'verbose_name_plural': 'Student Learning Profiles',
                'db_table': 'student_learning_profiles',
            },
        ),
    ]
