# Generated by Django 5.2.11 on 2026-04-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_studentlearningprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSessionProfile',
        ),
    ]
