# Generated by Django 5.2.11 on 2026-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
