# Generated by Django 5.2.11 on 2026-06-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_lessoncompletion_time_spent_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentRetrainingCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_since_last_train', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=50)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intent Retraining Counter',
                'verbose_name_plural': 'Intent Retraining Counter',
                'db_table': 'intent_retraining_counter',
            },
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='feedback',
            field=models.CharField(blank=True, choices=[('thumbs_up', '👍 Thumbs Up'), ('thumbs_down', '👎 Thumbs Down')], db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='intent_probabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='predicted_intent',
            field=models.CharField(blank=True, choices=[('On-Topic Question', 'On-Topic Question'), ('Off-Topic Question', 'Off-Topic Question'), ('Emotional-State', 'Emotional-State'), ('Pace-Related', 'Pace-Related'), ('Repeat/clarification', 'Repeat/clarification'), ('Debugging/Code-Sharing', 'Debugging/Code-Sharing')], db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='session_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='used_for_retraining',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='IntentFeedbackBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_input', models.TextField()),
                ('session_context', models.TextField(blank=True, default='')),
                ('predicted_intent', models.CharField(choices=[('On-Topic Question', 'On-Topic Question'), ('Off-Topic Question', 'Off-Topic Question'), ('Emotional-State', 'Emotional-State'), ('Pace-Related', 'Pace-Related'), ('Repeat/clarification', 'Repeat/clarification'), ('Debugging/Code-Sharing', 'Debugging/Code-Sharing')], max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('feedback', models.CharField(choices=[('thumbs_up', '👍 Thumbs Up'), ('thumbs_down', '👎 Thumbs Down')], max_length=16)),
                ('corrected_intent', models.CharField(blank=True, choices=[('On-Topic Question', 'On-Topic Question'), ('Off-Topic Question', 'Off-Topic Question'), ('Emotional-State', 'Emotional-State'), ('Pace-Related', 'Pace-Related'), ('Repeat/clarification', 'Repeat/clarification'), ('Debugging/Code-Sharing', 'Debugging/Code-Sharing')], db_index=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used for Retraining'), ('relabelled', 'Relabelled')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('chat_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_buffer_entry', to='progress.aichatlog')),
            ],
            options={
                'verbose_name': 'Intent Feedback Buffer Entry',
                'verbose_name_plural': 'Intent Feedback Buffer Entries',
                'db_table': 'intent_feedback_buffer',
                'ordering': ['-created_at'],
            },
        ),
    ]
