# Generated by Django 5.2.11 on 2026-06-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_lessoncompletion_time_spent_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlearningprofile',
            name='concept_mastery',
            field=models.JSONField(default=dict, help_text='Keys are concept IDs (str). Per-entry shape: {score: 0.0-1.0, evidence: int, trend: up|flat|down, last_updated: iso, linked_mistakes: []}.'),
        ),
    ]
