# Generated by Django 5.2.11 on 2026-06-14 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_studentlearningprofile_concept_mastery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptMasteryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(help_text='Django Concept.id (string) — matches concept_mastery projection keys.', max_length=64)),
                ('outcome', models.FloatField(help_text='Observed outcome 0.0–1.0 (fail→pass).')),
                ('source', models.CharField(choices=[('assessment', 'Placement assessment'), ('checkpoint', 'In-session MCQ checkpoint'), ('problem_set', 'Problem set'), ('capstone_grade', 'Capstone grade'), ('capstone_assist', 'Capstone assist penalty'), ('backfill', 'Migration backfill seed')], max_length=20)),
                ('alpha', models.FloatField(default=0.3, help_text='Per-event EMA weight. Lets callers (e.g. Batch 10) down-weight an update without the mastery code knowing why.')),
                ('evidence_delta', models.IntegerField(default=1, help_text='How much independent evidence this event contributes. 0 for assist penalties (not new independent demonstration); for backfill seeds, the prior evidence count.')),
                ('mistake_tag', models.CharField(blank=True, default='', max_length=120)),
                ('seed_meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mastery_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'concept_mastery_events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['student', 'concept_id', 'created_at', 'id'], name='concept_mas_student_226600_idx')],
            },
        ),
    ]
