# Generated by Django 5.2.11 on 2026-06-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_backfill_concept_mastery_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlearningprofile',
            name='profile_version',
            field=models.IntegerField(default=0),
        ),
    ]
