# Generated by Django 5.2.11 on 2026-06-15 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursecorpus_corpussource'),
        ('progress', '0012_lessoncompletion_gamification_awarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_version', models.IntegerField()),
                ('kind', models.CharField(default='review', max_length=20)),
                ('trigger_threshold', models.FloatField()),
                ('score_at_trigger', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_steps', to='courses.concept')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_steps', to='courses.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_steps', to='courses.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remediation_steps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'plan_version', 'status'], name='remediation_enrollm_17d984_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('enrollment', 'plan_version', 'concept'), name='uniq_open_remediation_per_concept')],
            },
        ),
    ]
