# Generated by Django 5.2.11 on 2026-06-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_intentretrainingcounter_aichatlog_confidence_and_more'),
        ('progress', '0014_emotionconsent'),
    ]

    operations = [
    ]
