# Generated by Django 5.2.11 on 2026-06-17 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_lesson_module_remove_concept_lessons_and_more'),
        ('progress', '0015_merge_20260615_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatlog',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),

        migrations.AddField(
            model_name='aichatlog',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_logs', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SessionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Started', 'Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Started', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('gamification_awarded', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_completions', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Session Completion',
                'verbose_name_plural': 'Session Completions',
                'db_table': 'session_completions',
                'ordering': ['-completed_at'],
                'unique_together': {('enrollment', 'session_number')},
            },
        ),
        migrations.DeleteModel(
            name='LessonCompletion',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'course', 'session_number', 'slide_index')},
        ),
    ]
