# Generated by Django 5.2.11 on 2026-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0017_studentlearningprofile_profile_summary_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatlog',
            name='corrected_intent',
            field=models.CharField(blank=True, choices=[('On-Topic Question', 'On-Topic Question'), ('Off-Topic Question', 'Off-Topic Question'), ('Emotional-State', 'Emotional-State'), ('Pace-Related', 'Pace-Related'), ('Repeat/clarification', 'Repeat/clarification'), ('Debugging/Code-Sharing', 'Debugging/Code-Sharing')], db_index=True, max_length=30, null=True),
        ),
    ]
