# Generated by Django 5.2.11 on 2026-06-14 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text="Machine-readable action name, e.g. 'retrain_intent', 'reset_enrollment'.", max_length=100)),
                ('target_type', models.CharField(blank=True, default='', help_text="Model or resource type affected, e.g. 'Enrollment', 'User'.", max_length=100)),
                ('target_id', models.CharField(blank=True, default='', help_text='Primary key or identifier of the affected resource.', max_length=100)),
                ('snapshot_before', models.JSONField(blank=True, help_text='JSON snapshot of the resource state before the action.', null=True)),
                ('snapshot_after', models.JSONField(blank=True, help_text='JSON snapshot of the resource state after the action.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='admin_audit_admin_i_448b62_idx'), models.Index(fields=['action', 'created_at'], name='admin_audit_action_7451ef_idx')],
            },
        ),
    ]
