# Generated by Django 5.2.11 on 2026-06-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_coursecorpus_corpussource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_version', models.IntegerField()),
                ('generation_index', models.IntegerField(default=0)),
                ('ps_uid', models.CharField(max_length=64, unique=True)),
                ('content_json', models.JSONField(default=dict)),
                ('storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('hint_tracking', models.JSONField(default=dict)),
                ('superseded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='courses.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artifact_problem_sets',
                'ordering': ['enrollment_id', 'lesson_id', 'generation_index'],
            },
        ),
        migrations.CreateModel(
            name='ProblemSetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=64)),
                ('code', models.TextField(blank=True, default='')),
                ('evaluated_rubric', models.JSONField(default=list)),
                ('hints_used', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('original', 'Original'), ('regenerated', 'Regenerated'), ('imported', 'Imported')], default='original', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='artifacts.problemset')),
            ],
            options={
                'db_table': 'artifact_problem_set_attempts',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('slides', 'Slides'), ('lab', 'Lab')], max_length=20)),
                ('session_number', models.IntegerField(blank=True, null=True)),
                ('plan_version', models.IntegerField()),
                ('generation_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='generated', max_length=20)),
                ('content_json', models.JSONField(default=dict)),
                ('storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='courses.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='courses.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artifact_student_artifacts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=list)),
                ('per_question', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('concept_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to='courses.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to='courses.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artifact_placement_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', '-created_at'], name='artifact_pl_enrollm_35d94b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='problemset',
            index=models.Index(fields=['enrollment', 'lesson', 'plan_version'], name='artifact_pr_enrollm_11b1d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemset',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson', 'plan_version', 'generation_index'), name='uniq_problem_set_generation'),
        ),
        migrations.AddIndex(
            model_name='problemsetattempt',
            index=models.Index(fields=['problem_set', 'question_id', 'created_at'], name='artifact_pr_problem_d42eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentartifact',
            index=models.Index(fields=['enrollment', 'artifact_type', 'plan_version'], name='artifact_st_enrollm_a8146d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentartifact',
            constraint=models.UniqueConstraint(fields=('enrollment', 'artifact_type', 'session_number', 'lesson', 'plan_version', 'generation_index'), name='uniq_student_artifact_key'),
        ),
    ]
