# Generated by Django 5.2.11 on 2026-06-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
