# Generated by Django 5.2.11 on 2026-06-17 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_problemset_num_questions'),
        ('courses', '0009_corpussource_chunk_count_corpussource_index_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemset',
            options={'ordering': ['enrollment_id', 'session_number', 'generation_index']},
        ),
        migrations.RemoveConstraint(
            model_name='problemset',
            name='uniq_problem_set_generation',
        ),
        migrations.RemoveConstraint(
            model_name='studentartifact',
            name='uniq_student_artifact_key',
        ),
        migrations.RemoveIndex(
            model_name='problemset',
            name='artifact_pr_enrollm_11b1d1_idx',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='studentartifact',
            name='lesson',
        ),
        migrations.AddField(
            model_name='problemset',
            name='session_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='problemset',
            index=models.Index(fields=['enrollment', 'session_number', 'plan_version'], name='artifact_pr_enrollm_a68a5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemset',
            constraint=models.UniqueConstraint(fields=('enrollment', 'session_number', 'plan_version', 'generation_index'), name='uniq_problem_set_generation'),
        ),
        migrations.AddConstraint(
            model_name='studentartifact',
            constraint=models.UniqueConstraint(fields=('enrollment', 'artifact_type', 'session_number', 'plan_version', 'generation_index'), name='uniq_student_artifact_key'),
        ),
    ]
