# Generated by Django 5.2.11 on 2026-06-06 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_concept_courselearningoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_json', models.JSONField(default=dict)),
                ('response_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_summary', to='courses.course')),
            ],
            options={
                'verbose_name': 'Survey Summary',
                'verbose_name_plural': 'Survey Summaries',
                'db_table': 'survey_summaries',
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_templates', to='courses.course')),
            ],
            options={
                'verbose_name': 'Survey Template',
                'verbose_name_plural': 'Survey Templates',
                'db_table': 'survey_templates',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(help_text='Dict of {question_id: answer_value}.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='courses.enrollment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.surveytemplate')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'db_table': 'survey_responses',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('likert', 'Likert (1-5)'), ('text', 'Free Text'), ('single', 'Single Choice'), ('multi', 'Multiple Choice')], max_length=10)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('clo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='courses.courselearningoutcome')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.surveytemplate')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'db_table': 'survey_questions',
                'ordering': ['order'],
            },
        ),
    ]
