"""Document plan schema for presentation structure."""

from pydantic import BaseModel, Field


class Section(BaseModel):
    """A topic section discovered from the document."""

    id: int = Field(description="Section index (0-based)")
    title: str = Field(description="Auto-generated section title")
    chunks: list[str] = Field(
        default_factory=list,
        description="Text chunks belonging to this section"
    )
    chunk_indices: list[int] = Field(
        default_factory=list,
        description="Original indices of the chunks in the full chunk list"
    )


class DocumentPlan(BaseModel):
    """
    Structural plan for a presentation deck.

    Generated by the Document Processor from a raw PDF.
    Contains the document title and ordered list of topic sections.
    """

    title: str = Field(description="Auto-generated document/presentation title")
    sections: list[Section] = Field(
        default_factory=list,
        description="Ordered list of topic sections"
    )

    @property
    def total_chunks(self) -> int:
        """Total number of content chunks across all sections."""
        return sum(len(s.chunks) for s in self.sections)

    @property
    def section_titles(self) -> list[str]:
        """List of all section titles in order."""
        return [s.title for s in self.sections]
