# Generated by Django 5.2.11 on 2026-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_assessment_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_pathway_ready',
            field=models.BooleanField(default=False),
        ),
    ]
