# Generated by Django 5.2.11 on 2026-05-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_is_assessment_started_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
