# Generated by Django 5.2.11 on 2026-06-06 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='courses.course')),
                ('lessons', models.ManyToManyField(blank=True, related_name='concepts', to='courses.lesson')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.concept')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
                'db_table': 'concepts',
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='E.g. CLO1, CLO2', max_length=20)),
                ('text', models.TextField()),
                ('bloom_level', models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('concepts', models.ManyToManyField(blank=True, related_name='clos', to='courses.concept')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Learning Outcome',
                'verbose_name_plural': 'Course Learning Outcomes',
                'db_table': 'course_learning_outcomes',
                'ordering': ['order'],
                'unique_together': {('course', 'code')},
            },
        ),
    ]
