# Generated by Django 5.2.11 on 2026-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursecorpus_corpussource'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpussource',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corpussource',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
