# Generated by Django 5.2.11 on 2026-06-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_corpussource_chunk_count_corpussource_index_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='current_lesson',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_lessons_count',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_session_number',
            field=models.IntegerField(default=1, help_text="The current active session in the student's pathway."),
        ),
        migrations.DeleteModel(
            name='CodeChallenge',
        ),
    ]
