# Generated by Django 5.2.11 on 2026-06-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_alter_problemset_options_and_more'),
        ('courses', '0010_remove_lesson_module_remove_concept_lessons_and_more'),
        ('progress', '0016_remove_aichatlog_lesson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
