# Generated by Django 5.2.11 on 2026-06-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_placementquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-extracted')], default='manual', help_text='How this concept was created (manual admin entry vs. auto-extracted from a book).', max_length=20),
        ),
    ]
