# Generated by Django 5.2.11 on 2026-06-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_add_concept_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLOConceptTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_topics', models.JSONField(blank=True, default=list)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_topics', to='courses.courselearningoutcome')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_topic_selections', to='courses.concept')),
            ],
            options={
                'verbose_name': 'CLO Concept Topic Selection',
                'verbose_name_plural': 'CLO Concept Topic Selections',
                'db_table': 'clo_concept_topics',
                'unique_together': {('clo', 'concept')},
            },
        ),
    ]
