# Generated by Django 5.2.11 on 2026-06-06 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_concept_courselearningoutcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('spec_mode', models.CharField(choices=[('admin_defined', 'Admin-defined'), ('student_proposed', 'Student-proposed')], default='admin_defined', max_length=20)),
                ('team_mode', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], default='solo', max_length=10)),
                ('team_cap', models.PositiveIntegerField(default=4)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('brief_text', models.TextField(blank=True)),
                ('github_template_repo', models.CharField(blank=True, max_length=300)),
                ('run_command', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstones', to='courses.course')),
            ],
            options={
                'db_table': 'capstones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('planned_features', models.JSONField(default=list)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_feedback', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='capstone.capstone')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capstone_proposals',
                'ordering': ['-submitted_at'],
                'unique_together': {('capstone', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CapstoneRubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('core', 'Core'), ('stretch', 'Stretch')], default='core', max_length=10)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('min_team_size', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_items', to='capstone.capstone')),
                ('clo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capstone_items', to='courses.courselearningoutcome')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capstone_items', to='courses.concept')),
            ],
            options={
                'db_table': 'capstone_rubric_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True)),
                ('latest_commit_sha', models.CharField(blank=True, max_length=40)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('results', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='capstone.capstone')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_submissions', to='courses.enrollment')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='capstone.capstoneproposal')),
            ],
            options={
                'db_table': 'capstone_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
