# Generated by Django 5.2.11 on 2026-06-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
        ('courses', '0006_concept_courselearningoutcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capstonesubmission',
            name='branch',
            field=models.CharField(default='work', max_length=100),
        ),
        migrations.AddField(
            model_name='capstonesubmission',
            name='contributions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CapstoneAssistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_logs', to='capstone.capstone')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capstone_assist_logs', to='courses.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_assist_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capstone_assist_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('submitted', 'Submitted'), ('disbanded', 'Disbanded')], default='forming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='capstone.capstone')),
                ('members', models.ManyToManyField(blank=True, related_name='capstone_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capstone_teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='capstonesubmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='capstone.team'),
        ),
        migrations.CreateModel(
            name='MatchmakingQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('expired', 'Expired')], default='waiting', max_length=10)),
                ('fill_window_expires_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='capstone.capstone')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='capstone.team')),
            ],
            options={
                'db_table': 'capstone_matchmaking_queue',
                'ordering': ['joined_at'],
                'unique_together': {('capstone', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CapstoneAssistQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('used', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=10)),
                ('period_start', models.DateTimeField(auto_now_add=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_quotas', to='capstone.capstone')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capstone_assist_quotas', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist_quotas', to='capstone.team')),
            ],
            options={
                'db_table': 'capstone_assist_quotas',
                'unique_together': {('capstone', 'student')},
            },
        ),
    ]
