# Generated by Django 5.2.11 on 2026-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_capstonesubmission_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstonesubmission',
            name='mastery_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capstonesubmission',
            name='xp_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
