# Generated by Django 5.2.11 on 2026-06-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_capstonesubmission_mastery_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstone',
            name='pass_policy',
            field=models.CharField(choices=[('all_core', 'All core criteria must pass')], default='all_core', help_text="Rule for the PASS/FAIL verdict. 'all_core' = every core criterion must pass.", max_length=20),
        ),
        migrations.AddField(
            model_name='capstonesubmission',
            name='verdict',
            field=models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=10),
        ),
    ]
