# Generated by Django 5.2.11 on 2026-06-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_capstone_pass_policy_capstonesubmission_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role_advice',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='role_advice_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
