# Generated by Django 5.2.11 on 2026-06-23 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_capstone_ci_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capstoneproposal',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='capstone.team'),
        ),
        migrations.AddField(
            model_name='capstonerubricitem',
            name='checks',
            field=models.JSONField(blank=True, default=list, help_text='Atomic binary sub-checks: [{id, text}]. Criterion passes iff all checks pass.'),
        ),
        migrations.AddField(
            model_name='team',
            name='branch',
            field=models.CharField(default='work', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='capstoneproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('capstone', 'team'), name='uniq_team_proposal'),
        ),
    ]
