# Generated by Django 5.2.11 on 2026-06-23 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_capstoneproposal_team_capstonerubricitem_checks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capstoneproposal',
            name='agreed_members',
            field=models.ManyToManyField(blank=True, related_name='agreed_capstone_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchmakingqueueentry',
            name='declined_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='confirmed_members',
            field=models.ManyToManyField(blank=True, related_name='confirmed_capstone_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
