from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from .models import Lesson, Course, CourseCorpus


def _update_course_lesson_count(lesson):
    course = lesson.module.course
    count = Lesson.objects.filter(module__course=course).count()
    Course.objects.filter(pk=course.pk).update(total_lessons_count=count)


@receiver(post_save, sender=Lesson)
def lesson_saved(sender, instance, **kwargs):
    _update_course_lesson_count(instance)


@receiver(post_delete, sender=Lesson)
def lesson_deleted(sender, instance, **kwargs):
    _update_course_lesson_count(instance)


@receiver(post_save, sender=Course)
def ensure_course_corpus(sender, instance, created, **kwargs):
    """Every course gets exactly one corpus, created the moment the course is.

    Keeps the invariant "one explicit corpus per course" true without relying on
    an admin remembering to create it. corpus_id is generated by the model default.
    """
    if created:
        CourseCorpus.objects.get_or_create(
            course=instance, defaults={"name": instance.title},
        )
